name: orders_performance

default_connections:
  duckdb: "duckdb-default"
  postgres: "pg-default"

variables:
  all_time:
    type: int
    default: 1 # 0 for all time - 1 to enable start_date and end_date